### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'final_recipe1msubs_val.pkl'

### ISSUE THREAD

**Issue by PoomrapeeWareeboutr** [facebookresearch/gismo#3]
I tried to export `model_and_module.torch` for use in `FullGismoInference.ipynb` but when I ran this command

```
python visualize.py task=im2recipe \
        dataset.ablation.with_substitutions=True \
        name=eval_im2recipe_vit16_multi_level_recipe_inference \
        eval_checkpoint_dir=<<PATH_2>>
```

It shows the following error that is a file `final_recipe1msubs_val.pkl` is not found. I tried to find the source to download the file in the `README.md` instructions but it does not exist for this file.

```
<frozen importlib._bootstrap>:219: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
C:\Users\ADMIN\Desktop\proj\gismo\inv_cooking\scheduler\scheduler.py:20: UserWarning: register_resolver() is deprecated.
See https://github.com/omry/omegaconf/issues/426 for migration instructions.

  OmegaConf.register_resolver("slurm_job_id", get_job_id)
C:\Users\ADMIN\anaconda3\envs\gismo\lib\site-packages\hydra\core\utils.py:143: UserWarning: register_resolver() is deprecated.
See https://github.com/omry/omegaconf/issues/426 for migration instructions.

  OmegaConf.register_resolver(name, f)
C:\Users\ADMIN\anaconda3\envs\gismo\lib\site-packages\hydra\_internal\config_loader_impl.py:909: UserWarning: `OmegaConf.is_none()` is deprecated, see https://github.com/omry/omegaconf/issues/547
  if not (cfg._is_missing() or OmegaConf.is_none(cfg)):
C:\Users\ADMIN\anaconda3\envs\gismo\lib\site-packages\hydra\_internal\config_loader_impl.py:914: UserWarning: `OmegaConf.is_none()` is deprecated, see https://github.com/omry/omegaconf/issues/547
  if not (cfg._is_missing() or OmegaConf.is_none(cfg)):
Copying ['inv_cooking', 'data'] from C:\Users\ADMIN\Desktop\proj\gismo to C:\path\to\artifact\inversecooking2\local\im2recipe-eval_im2recipe_vit16_multi_level_recipe_inference\2023-10-14_15-35-26...
Copying done. Running code in folder C:\path\to\artifact\inversecooking2\local\im2recipe-eval_im2recipe_vit16_multi_level_recipe_inference\2023-10-14_15-35-26
Traceback (most recent call last):
  File "visualize.py", line 15, in main
    schedule_jobs(cfg, training_mode=TrainingMode.VISUALIZE)
  File "C:\Users\ADMIN\Desktop\proj\gismo\inv_cooking\scheduler\scheduler.py", line 40, in schedule_jobs
    schedule_job_locally(config, training_mode)
  File "C:\Users\ADMIN\Desktop\proj\gismo\inv_cooking\scheduler\scheduler.py", line 61, in schedule_job_locally
    run_visualisation(cfg)
  File "C:\Users\ADMIN\Desktop\proj\gismo\inv_cooking\training\visualise.py", line 34, in run_visualisation
    data_module.setup("test")
  File "C:\Users\ADMIN\anaconda3\envs\gismo\lib\site-packages\pytorch_lightning\core\datamodule.py", line 92, in wrapped_fn
    return fn(*args, **kwargs)
  File "C:\Users\ADMIN\Desktop\proj\gismo\inv_cooking\datasets\recipe1m\loader.py", line 61, in setup
    self.dataset_test = self._get_dataset("val", eval_split)
  File "C:\Users\ADMIN\Desktop\proj\gismo\inv_cooking\datasets\recipe1m\loader.py", line 117, in _get_dataset
    dataset = Recipe1M(
  File "C:\Users\ADMIN\Desktop\proj\gismo\inv_cooking\datasets\recipe1m\dataset.py", line 139, in __init__
    open(
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/ADMIN/Desktop/proj/gismo/inv_cooking/datasets/recipe1m/preprocessed_flavorgraph_substitutions_fixed_3\\final_recipe1msubs_val.pkl'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

How do I get that file or am I missing some steps?

**Comment by PoomrapeeWareeboutr** [comment]
And if you please, could you give me a download source for the Recipe1M dataset. Now it cannot be accessed by the link provided in the instructions. I have to use the structure of the dataset to reproduce the experiment with my data.

**Comment by ENVY-S** [comment]
Hey friend! Have you solved the problem of getting the dataset? I've also encountered the same problem and am wondering how to solve it. If you get it, can you send me a copy? Greatful!
